include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - avoid_private_typedef_functions
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - package_api_docs
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_locals
    - unnecessary_breaks
    - use_string_buffers
