name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'

jobs:
  analyze_and_format:
    runs-on: ubuntu-latest
    steps:
    - uses: cedx/setup-dart@v2
      with:
        release-channel: dev
    - uses: actions/checkout@v2

    - run: pub get

    - run: dart format --output=none --set-exit-if-changed .
    - run: dart analyze --fatal-warnings --fatal-infos .
  test:
    strategy:
      matrix:
       os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: cedx/setup-dart@v2
      with:
        release-channel: dev
    - uses: actions/checkout@v2

    - run: pub get
    - run: dart test -p vm,chrome
